name: upload-test-report
description: "Uploads the unit test reports"

inputs:
  report-name:
    description: "Name of the report to be upload."
    required: true

runs:
  using: composite
  steps:
    - name: Collect Test Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test_report_${{ inputs.report-name }}
        path: |
          reports/**
          ./build/Testing/Temporary/*.log
          /var/lib/systemd/coredump/**
          /var/log/syslog